function processWindow(app)
    win = LoadDisplayWindow();

    %AtlasView
    win.addStep('AtlasView', struct( ...
        'Load', @() loadAV(app, []), ...
        'Display', @() plotSD(app, []) ...
    ));

    % Sensitivity
    win.addStep('Sensitivity', struct( ...
        'Load', @() loadSens(app), ...
        'Display_Brain', @() plotSensitivity(app), ...
        'Display_Head', @() plotSensitivity(app) ...
    ));
end
